version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: asd123       
      MYSQL_DATABASE: cepSearch         
      MYSQL_USER: sa               		
      MYSQL_PASSWORD: sa               
    ports:
      - "3306:3306"                    
    volumes:
      - mysql-data:/var/lib/mysql      
    networks:
      - mysql-network

volumes:
  mysql-data:

networks:
  mysql-network:
    driver: bridge