spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cepSearch
    username: root
    password: asd123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update  # Ou 'create', 'create-drop', dependendo de sua necessidade
    database-platform: org.hibernate.dialect.MySQL8Dialect
viacep:
  url: "https://viacep.com.br/ws"

